<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Testing" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Src\BikeBuilder.API\BikeBuilder.API.csproj" />
    <ProjectReference Include="..\..\Src\BikeBuilder.AppHost\BikeBuilder.AppHost.csproj" />
    <ProjectReference Include="..\..\Src\BikeBuilder.DataSeeder\BikeBuilder.DataSeeder.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="TestAssets\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>